# Generated by Django 3.2 on 2021-05-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0002_auto_20210501_1632'),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.CharField(max_length=50, verbose_name='Habilidad')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades de Empleados',
            },
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'People', 'verbose_name_plural': 'Gentes'},
        ),
        migrations.AlterUniqueTogether(
            name='persona',
            unique_together={('first_name', 'last_name', 'departamento')},
        ),
    ]
