# Generated by Django 3.2 on 2021-05-01 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0002_auto_20210501_1632'),
        ('persona', '0005_rename_persona_empleado'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empleado',
            new_name='Persona',
        ),
    ]
