# Generated by Django 3.2 on 2021-05-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0007_persona_hoja_vida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
        migrations.AddField(
            model_name='persona',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nombre completo'),
        ),
    ]
